### ISSUE TITLE
Error on Script on Run

### ISSUE THREAD

**Issue by sheastech** [nutanixdev/udacity#1]
Error given on script upon running..

.calm/ceeb9858-a472-428d-88a9-e66817/MWI5MmY2MzdkOTljMTllMzY1MGY2Nz: line 1: CREATE: command not found
.calm/ceeb9858-a472-428d-88a9-e66817/MWI5MmY2MzdkOTljMTllMzY1MGY2Nz: line 2: syntax error near unexpected token `('
.calm/ceeb9858-a472-428d-88a9-e66817/MWI5MmY2MzdkOTljMTllMzY1MGY2Nz: line 2: `CREATE TABLE IF NOT EXISTS webapp.tecc_dba_test ( \'

**Comment by sheastech** [comment]
**### Syntax error on line 2...**

CREATE DATABASE IF NOT EXISTS webapp ;
CREATE TABLE IF NOT EXISTS webapp.tecc_dba_test ( \
  id INT NOT NULL AUTO_INCREMENT , \
  time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP , \
  comment VARCHAR(80) NULL DEFAULT NULL , \
  PRIMARY KEY (id)) \
  ENGINE = InnoDB CHARSET=ascii COLLATE ascii_general_ci COMMENT = 'testing';

FLUSH PRIVILEGES;
CREATE USER 'tecc_webuser'@'%' IDENTIFIED WITH mysql_native_password BY 'end-user-provided-password' \
  REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
GRANT SELECT, INSERT ON *.* TO 'tecc_webuser'@'%';

CREATE USER 'tecc_webuser'@'localhost' IDENTIFIED WITH mysql_native_password BY 'end-user-provided-password' \
  REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
GRANT SELECT, INSERT ON *.* TO 'tecc_webuser'@'localhost';

FLUSH PRIVILEGES;

**Comment by mlavi** [comment]
@migrationking Sorry for the delay, didn't see this! Assuming this isn't reproducable, please reopen if needed!
